2020-04-14 04:02:00,702 ERROR: Exception on /index [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\routes.py", line 29, in index
    posts = current_user.folLowed_posts().paginate(page, app.config['POST_PER_PAGE'], False)
  File "c:\users\microsoft\microblog\env\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'folLowed_posts'
2020-04-14 04:02:12,249 ERROR: Exception on /index [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\routes.py", line 29, in index
    posts = current_user.folLowed_posts().paginate(page, app.config['POST_PER_PAGE'], False)
  File "c:\users\microsoft\microblog\env\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'folLowed_posts'
2020-04-14 04:02:27,016 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:02:32,021 ERROR: Exception on /index [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\routes.py", line 29, in index
    posts = current_user.followed_posts().paginate(page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-04-14 04:02:35,243 ERROR: Exception on /index [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\routes.py", line 29, in index
    posts = current_user.followed_posts().paginate(page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-04-14 04:03:12,468 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:09:48,997 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:13:33,198 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:16:38,262 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:18:44,344 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:23:58,717 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:24:37,023 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:30:53,088 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:33:15,562 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:35:26,923 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:44:21,116 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 04:45:47,912 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:45]
2020-04-14 05:03:04,960 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-14 06:35:50,889 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-14 06:37:27,704 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-14 06:44:27,906 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-14 06:45:47,758 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-14 06:59:33,017 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:46]
2020-04-15 05:27:29,923 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:47]
2020-04-15 05:31:15,141 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:47]
2020-04-15 05:52:13,237 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:48]
2020-04-21 08:03:56,234 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:48]
2020-04-21 08:17:34,965 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:48]
